# START
id1: str = input("Enter the first id number: ")
first_name1: str = input("Enter the first first name: ")
last_name1: str = input("Enter the first last name: ")
height1: float = float(input("Enter the first height: "))
birth_year1: int = int(input("Enter the first birth year: "))
id2: str = input("Enter the second id number: ")
first_name2: str = input("Enter the second first name: ")
last_name2: str = input("Enter the second last name: ")
height2: float = float(input("Enter the second height: "))
birth_year2: int = int(input("Enter the second birth year: "))
id3: str = input("Enter the third id number: ")
first_name3: str = input("Enter the third first name: ")
last_name3: str = input("Enter the third last name: ")
height3: float = float(input("Enter the third height: "))
birth_year3: int = int(input("Enter the third birth year: "))
print(f"id: {id1:<5}, name: {last_name1:<9},{first_name1:>10}, height: {height1:<5}, year of birth:{birth_year1:<4}")
print(f"id: {id2:<5}, name: {last_name2:<9},{first_name2:>10}, height: {height2:<5}, year of birth:{birth_year2:<4}")
print(f"id: {id3:<5}, name: {last_name3:<9},{first_name3:>10}, height: {height3:<5}, year of birth:{birth_year3:<4}")
# STOP
